[package]
name = "shodan_api"
version = "0.1.0"
authors = ["Daniel Hoberecht <danhsecure@gmail.com"]
license = "GPL-3.0"
description = "A Rusty wrapper for the Shodan.io API."
edition = "2018"


[dependencies]
reqwest = {version = "0.11.0", features = ["blocking"]}
